sudo: false
language: scala

scala:
  - 2.11.12
  - 2.12.8

jdk:
  - openjdk8

sbt_args: -J-Xmx8192M

install:
  - pip install --user codecov

script:
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalastyle scalafmtCheck scalafmtSbtCheck test:scalafmtCheck unidoc coverageReport && codecov;
