sudo: false
language: scala

scala:
  - 2.11.12
  - 2.12.4

jdk:
  - oraclejdk8

sbt_args: -J-Xmx4096M

install:
  - pip install --user codecov

script:
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalastyle unidoc coverageReport && codecov;
